### ISSUE TITLE
upgrade dependencies

### ISSUE THREAD

**Issue by charlieforward9** [felixblaschke/flutterplasma#11]
I had to do a little debugging with the simple animations package because the PlasmaRenderer class was not recognized. Not sure if they got rid of it or renamed it in a newer version, but I have to bring my code version down from 5.0.0^ to 3.0.3^ in order to get it working. 

The specific location of the bug is on [this file](https://github.com/felixblaschke/flutterplasma/blob/90394b992e34e0ee90f76b77f321d51705191f4f/lib/demo/fancy_plasma1/fancy_widgets1.dart), line 31

I will open an issue in the simple_animations repo to request better documentation, but I figure I'd open this one too to keep the demo fresh given I found it on [Flutter Showcase](https://flutter.dev/showcase). 

Finally,  thank you for making this! I am copying this fancy plasma code to use on my splash screen and appreciate the open-source work!

**Comment by felixblaschke** [comment]
As stated in changelog (https://github.com/felixblaschke/simple_animations/blob/main/CHANGELOG.md#400) with 4.x the Liquid/Plasma feature got extracted into an own package: https://pub.dev/packages/sa3_liquid

I won't add any new features to it, but you can use in the state as it currently is.
