### ISSUE TITLE
flutterplasma.dev was hacked

### ISSUE THREAD

**Issue by varolagos** [felixblaschke/flutterplasma#12]
The site redirects to an advertisement stating that the computer was infected

<img width="1449" alt="Xnip2023-12-14_18-39-10" src="https://github.com/felixblaschke/flutterplasma/assets/5040082/c5536c18-628f-4479-aebf-026719952512">

**Comment by felixblaschke** [comment]
Hi. Thanks for the report. No it wasn't hacked. The domain purchased for this demo got unsubscribed.
