### ISSUE TITLE
When I open the website, the CPU usage is still relatively high.

### ISSUE THREAD

**Issue by Aaron009** [felixblaschke/flutterplasma#8]
surroundings:
mac os 10.15
chrome latest version stable
cpu occupies about 40%

Personally feel worse than Flash experience

**Comment by felixblaschke** [comment]
Thank you for the feedback and your observation are right. This demo isn't targeted as usual web application. It's more some kind of tech-demo squeezing a lot of power from your device (like a computer game). It's constantly rendering high-demand graphics (even if it might not look to you). More recent hardware (like the M1 macbook) will handle it just fine, but older devices struggle with it.
